version: '3.8'
services:
  api:
    build: .
    volumes:
      - ./app/:/code/app/
    command: uvicorn --factory app.main:create_app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000

  db:
    image: postgres:13.4-alpine
    volumes:
      - ~/.science/data/postgres:/var/lib/postgresql/data
      - ./data:/data
    env_file:
      - .env
    ports:
      - 5432:5432
